### ISSUE TITLE
{Question} The domain is not getting updated :/

### ISSUE THREAD

**Issue by AriaFantom** [swiftwave-org/dashboard#38]
![image](https://github.com/swiftwave-org/swiftwave-dashboard/assets/55119711/c53c3ea5-0537-442b-b9ef-be6b3adf3910)

Its shows me that its does not point :?

I added the ip and pointed 
![image](https://github.com/swiftwave-org/swiftwave-dashboard/assets/55119711/fdf2eae6-4ea4-4733-87f7-3fdffb032d71)

**Comment by tanmoysrt** [comment]
@AriaFantom are you using Cloudflare?

**Comment by tanmoysrt** [comment]
I just checked A records for your domain. It is pointing to your `Nginx Proxy Manager` actually.

**Comment by AriaFantom** [comment]
> @AriaFantom are you using Cloudflare?

no

**Comment by AriaFantom** [comment]
> I just checked A records for your domain. It is pointing to your `Nginx Proxy Manager` actually.

Actually i was testing so i put Nginx Proxy Manager later when i finished tesing ur app
and btw i am not using cloudflare but i am using nameserver of vercel and they have something called Edge network enabled so i think that might be a issue

**Comment by tanmoysrt** [comment]
> > I just checked A records for your domain. It is pointing to your `Nginx Proxy Manager` actually.
> 
> Actually i was testing so i put Nginx Proxy Manager later when i finished tesing ur app and btw i am not using cloudflare but i am using nameserver of vercel and they have something called Edge network enabled so i think that might be a issue

Yes can be, With cloudflare, if you have enabled proxy, this stuffs doesn't look to work, because while we enable proxy the actual IP got masked, also they are built to mainly support HTTP/HTTPS based application, not pure TCP based commnication.

You can check whether it's the same stuff like Cloudflare proxy

**Comment by tanmoysrt** [comment]
You can verify that manually yourself aswell
Forward the domain to Swiftwave server and try to access
```
http://<your_domain>/.well-known/pre-authorize/
```

if it giving you "OK" then it's fine.
We need to confirm this stuffs because Let's encrypt SSL generation failed if this checks not maintained.

Always if vercel automatically, forwarding http to https then also the problem arise, because `http-01` challenge works over http only

**Comment by tanmoysrt** [comment]
We are releasing new version soon and will not have any issue like this !
Thanks for trying out initial version of Swiftwave
